name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy-package-next:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        # NOTE(krishan711): need full history to calculate difference
        fetch-depth: 0
    - name: Build docker image
      run: docker build --tag package .
    # - name: Calculate commit count since last tag
    #   id: vars
    #   run: echo ::set-output name=commit_count::$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)
    # - name: Create .npmrc file
    #   run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    # - name: Publish next package to npm
    #   if: steps.vars.outputs.commit_count != '0'
    #   run: docker run -v $(pwd)/.npmrc:/root/.npmrc package /bin/bash -c "npm run publish-next -- --next-version ${{ steps.vars.outputs.commit_count }}"
